name: Usability Tests

on:
  pull_request:
    paths:
      - 'test/playwright/**'
      - '.github/workflows/usability.yml'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests (chromium)
        run: npx playwright test --project=chromium
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: usability-results
          path: test-results/
```yaml
name: Usability Tests
on:
  pull_request:
    paths:
      - 'test/playwright/**'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test --project=chromium
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: usability-results
          path: test-results/